# -*- coding: utf-8 -*-
"""image_pixellization_using_opencv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAeOh5tmEqGIa42xOk5TjO-NG2depUHJ
"""

from google.colab import drive, files                # now we assess the dataset from google drive
drive.mount('/content/drive/')
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

print(img[2,2])
cv2_imshow(img)

height=40
width=90
img=np.ones((height,width),dtype=np.uint8)*125

cv2_imshow(img)

img=np.ones((255,255),dtype=np.uint8)*125
img[0:90,0:30]=50
cv2_imshow(img)



img=np.array([
    [[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]

              ,[[16,17,18,19],[20,21,22,23],[24,25,36,81],[12,83,14,95]]

              ,[[0,10,20,30],[4,5,6,7],[8,9,10,100],[12,13,14,15]]

              ])

print(img[1,3,3])
cv2_imshow(img)

height=256
width=256
channel=3
img=np.ones((height,width,channel),dtype=np.uint8)*0

cv2_imshow(img)

img[0:30,0:255,0]=255#blue
img[31:90,0:50,1]=255#gree
img[90:255,0:250,2]=255#red

cv2_imshow(img)

height=290
width=290
channel=3
image=np.ones((height,width,channel),dtype=np.uint8)*0
cv2_imshow(image)
print(image.shape)

image[0:96,0:96,2]=255
image[0:96,96:192,0]=255
image[0:96,192:290,1]=255

image[96:192,0:96,1]=255
image[96:190,192:290,0]=255

image[192:290,0:96,2]=255
image[192:290,96:192,0]=255
image[192:290,192:290,2]=255



cv2_imshow(image)

cv2.imwrite('drive/MyDrive/image.jpg',image)